#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from nav_msgs.msg import Odometry
from geometry_msgs.msg import TransformStamped
import tf2_ros


class OdomToTF(Node):
    def __init__(self):
        super().__init__('odom_to_tf')
        self.broadcaster = tf2_ros.TransformBroadcaster(self)
        self.sub = self.create_subscription(
            Odometry,
            '/model/slam_drone/odometry',
            self.odom_callback,
            10
        )
        self.get_logger().info('odom_to_tf started')

    def odom_callback(self, msg):
        t = TransformStamped()
        t.header.stamp = msg.header.stamp
        t.header.frame_id = 'odom'
        t.child_frame_id = 'base_link'
        t.transform.translation.x = msg.pose.pose.position.x
        t.transform.translation.y = msg.pose.pose.position.y
        t.transform.translation.z = msg.pose.pose.position.z
        t.transform.rotation = msg.pose.pose.orientation
        self.broadcaster.sendTransform(t)


def main():
    rclpy.init()
    node = OdomToTF()
    rclpy.spin(node)


if __name__ == '__main__':
    main()
